list: $/livstag/boreholemanager/models/borehole/columns.yaml
modelClass: Livstag\BoreholeManager\Models\Borehole
title: Boreholes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'livstag/boreholemanager/boreholes/update/:id'
