name: Boreholes
form: $/livstag/boreholemanager/models/borehole/fields.yaml
modelClass: Livstag\BoreholeManager\Models\Borehole
defaultRedirect: livstag/boreholemanager/boreholes
create:
    redirect: 'livstag/boreholemanager/boreholes/update/:id'
    redirectClose: livstag/boreholemanager/boreholes
update:
    redirect: livstag/boreholemanager/boreholes
    redirectClose: livstag/boreholemanager/boreholes
